### ISSUE TITLE
Class error with transmute()

### ISSUE THREAD

**Issue by osymandius** [mrc-ide/naomi.utils#6] opened 2020-11-20 13:18 UTC
Transmute() throws error `Error: x must be a vector, not a data.frame/dhs_dataset object.` in `hr_extract_clusters()`. Can trigger with NGA or TGO.

```
areas <- NGA_or_TGO_areas
areas_wide <- spread_areas(areas)

surveys <- create_surveys_dhs(iso3, survey_characteristics = NULL) %>%
  filter(as.numeric(SurveyYear) > 1994)

survey_meta <- create_survey_meta_dhs(surveys)

survey_region_boundaries <- create_survey_boundaries_dhs(surveys)

surveys <- surveys_add_dhs_regvar(surveys, survey_region_boundaries)

survey_region_areas <- allocate_areas_survey_regions(areas_wide, survey_region_boundaries)

validate_survey_region_areas(survey_region_areas)

survey_regions <- create_survey_regions_dhs(survey_region_areas)

survey_clusters <- create_survey_clusters_dhs(surveys)

```

**Comment by osymandius** [comment] 2020-11-20 13:19
[I have no idea why only on some countries]

**Comment by jeffeaton** [comment] 2020-11-20 13:22
Can you try force reinstalling?  I think this is fixed by 0e53053bf. (Sorry didn't bump version number :/).

**Comment by osymandius** [comment] 2020-11-20 13:26
Still there I'm afraid.

**Comment by osymandius** [comment] 2020-11-20 13:42
+ Kenya
+ DRC
+ CMR
+ CIV
+ BFA
+ BDI

**Comment by jeffeaton** [comment] 2020-11-20 20:18
I am not able to reproduce this. Can you please post a reproducible example?

From the first issue, I would have anticipated the following should have demonstrated the error:

```r
library(naomi)
library(naomi.utils)
library(sf)

areas <- read_sf("~/naomi-data/TGO/data/tgo_areas.geojson")
areas_wide <- spread_areas(areas)

surveys <- create_surveys_dhs("TGO", survey_characteristics = NULL) 
survey_region_boundaries <- create_survey_boundaries_dhs(surveys)
surveys <- surveys_add_dhs_regvar(surveys, survey_region_boundaries)

survey_clusters <- create_survey_clusters_dhs(surveys)

sessionInfo()
```

Below is my output from this (no error):

```
> library(naomi)
> library(naomi.utils)
> library(sf)
Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1
> 
> areas <- read_sf("~/naomi-data/TGO/data/tgo_areas.geojson")
> areas_wide <- spread_areas(areas)
> 
> surveys <- create_surveys_dhs("TGO", survey_characteristics = NULL) 
...
> survey_region_boundaries <- create_survey_boundaries_dhs(surveys)
trying URL 
...
> surveys <- surveys_add_dhs_regvar(surveys, survey_region_boundaries)
> 
> survey_clusters <- create_survey_clusters_dhs(surveys)
Parsing HR dataset: TGO1998DHS
Parsing HR dataset: TGO2013DHS
Parsing HR dataset: TGO2017MIS
Loading required package: sp

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sp_1.4-4          sf_0.9-6          naomi.utils_0.0.1 naomi_2.0.4      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         compiler_4.0.2     pillar_1.4.6       forcats_0.5.0     
 [5] class_7.3-17       tools_4.0.2        digest_0.6.27      jsonlite_1.7.1    
 [9] lubridate_1.7.8    lifecycle_0.2.0    tibble_3.0.4       traduire_0.0.5    
[13] lattice_0.20-41    pkgconfig_2.0.3    rlang_0.4.8        Matrix_1.2-18     
[17] DBI_1.1.0          curl_4.3           haven_2.3.1        e1071_1.7-4       
[21] dplyr_1.0.2        storr_1.2.4        httr_1.4.2         hms_0.5.3         
[25] generics_0.1.0     vctrs_0.3.5        rdhs_0.7.1         rappdirs_0.3.1    
[29] classInt_0.4-3     grid_4.0.2         tidyselect_1.1.0   glue_1.4.2        
[33] R6_2.5.0           purrr_0.3.4        magrittr_2.0.1     ellipsis_0.3.1    
[37] units_0.6-7        V8_3.4.0           KernSmooth_2.23-17 crayon_1.3.4      
> 
```

**Closed as completed** 2020-11-23 10:06 UTC
